export type Marka = {
  naziv: string;
  domen: string;
};

export const MARKE: Marka[] = [
  { naziv: "Volkswagen", domen: "volkswagen.com" },
  { naziv: "Audi", domen: "audi.com" },
  { naziv: "BMW", domen: "bmw.com" },
  { naziv: "Mercedes-Benz", domen: "mercedes-benz.com" },
  { naziv: "Opel", domen: "opel.com" },
  { naziv: "Ford", domen: "ford.com" },
  { naziv: "Renault", domen: "renault.com" },
  { naziv: "Peugeot", domen: "peugeot.com" },
  { naziv: "Citroen", domen: "citroen.com" },
  { naziv: "Fiat", domen: "fiat.com" },
  { naziv: "Skoda", domen: "skoda-auto.com" },
  { naziv: "Seat", domen: "seat.com" },
  { naziv: "Toyota", domen: "toyota.com" },
  { naziv: "Honda", domen: "honda.com" },
  { naziv: "Nissan", domen: "nissan.com" },
  { naziv: "Mazda", domen: "mazda.com" },
  { naziv: "Hyundai", domen: "hyundai.com" },
  { naziv: "Kia", domen: "kia.com" },
  { naziv: "Volvo", domen: "volvocars.com" },
  { naziv: "Alfa Romeo", domen: "alfaromeo.com" },
  { naziv: "Dacia", domen: "dacia.com" },
  { naziv: "Mini", domen: "mini.com" },
  { naziv: "Porsche", domen: "porsche.com" },
  { naziv: "Land Rover", domen: "landrover.com" },
  { naziv: "Jaguar", domen: "jaguar.com" },
  { naziv: "Suzuki", domen: "suzuki.com" },
  { naziv: "Mitsubishi", domen: "mitsubishi-motors.com" },
  { naziv: "Subaru", domen: "subaru.com" },
  { naziv: "Lancia", domen: "lancia.com" },
  { naziv: "Chevrolet", domen: "chevrolet.com" },
  { naziv: "Jeep", domen: "jeep.com" },
  { naziv: "Smart", domen: "smart.com" },
  { naziv: "Tesla", domen: "tesla.com" },
  { naziv: "Lexus", domen: "lexus.com" },
  { naziv: "Infiniti", domen: "infiniti.com" },
  { naziv: "Cupra", domen: "cupraofficial.com" },
  { naziv: "DS", domen: "dsautomobiles.com" },
  { naziv: "SsangYong", domen: "ssangyong.com" },
  { naziv: "Chrysler", domen: "chrysler.com" },
  { naziv: "Saab", domen: "saab.com" },
];
